name: calendar_project_240727
description: "A new Flutter project."
publish_to: 'none'
version: 1.6.4+67
#version: 1.7.1+70

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 상태관리
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  # 데이터 모델링 직렬화
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # 데이터베이스
  sqflite: ^2.4.2
  path: ^1.9.1

  # 날짜 및 시간처리
  intl: ^0.20.2
  table_calendar:
    path: packages/table_calendar
  date_format: ^2.0.9
  dart_time: ^0.2.0

  # 입력 포매팅
  mask_text_input_formatter: ^2.9.0

  # 다트 유틸리티
  dartx: ^1.2.0
  collection: ^1.19.1

  # 파일 시스템 경로
  io: ^1.0.5

  # UI 컴포넌트 및 애니메이션
  fl_chart: ^1.1.1
  timer_builder: ^2.0.0
  percent_indicator: ^4.2.5
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.3.0
  flutter_styled_toast: ^2.3.0
  showcaseview: ^5.0.1
  flutter_svg: ^2.2.3
  animated_emoji: ^3.2.1
  material_design_icons_flutter: ^7.0.7296
  badges: ^3.1.2

  # 폼 처리
  formz: ^0.8.0
  flutter_form_builder: ^10.2.0

  # 페이지 전환
  go_router: ^17.0.1

  # 로컬 저장소
  shared_preferences: ^2.5.4

  # 푸시 알림
  firebase_core: ^4.3.0

  # 기타
  change_app_package_name: ^1.5.0

  # 데이터 압축
  archive: ^4.0.7

  # 리뷰
  in_app_review: ^2.0.11
  rxdart: ^0.28.0

  # 외부서비스
  firebase_remote_config: ^6.1.3
  firebase_analytics: ^12.1.0
  onesignal_flutter: ^5.3.4
  supabase_flutter: ^2.12.0

  # 디바이스 고유 ID 생성
  device_info_plus: ^11.4.0

  # 보안관련
  flutter_dotenv: ^5.2.1
  flutter_typeahead: ^5.2.0

  package_info_plus: ^8.3.0
  share_plus: ^12.0.1
  flutter_localization: ^0.3.3

  # https://pub.dev/packages/change_app_package_name/ 안드로이드,ios 패키지 네일 바꾸는 방법 참고
  # flutter pub run change_app_package_name:main com.app.calendar_project_240727 --android

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Icon/appstore.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - Icon/appstore.png
     - .env
     - packages/animated_emoji/lottie/rocket.json
     - packages/animated_emoji/lottie/waveMediumLight.json



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
